"""15th Migration

Revision ID: 113de6d3091c
Revises: 9150835300a3
Create Date: 2018-09-07 23:40:04.287170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113de6d3091c'
down_revision = '9150835300a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
