"""Migration

Revision ID: a367b6a52bc4
Revises: eb6c713e8d8b
Create Date: 2018-09-09 15:35:33.680405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a367b6a52bc4'
down_revision = 'eb6c713e8d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
