"""Migration

Revision ID: cddea033c038
Revises: a58d90ef7fd9
Create Date: 2018-09-10 11:52:23.402341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddea033c038'
down_revision = 'a58d90ef7fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitchs', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitchs', type_='foreignkey')
    op.drop_column('pitchs', 'category_id')
    # ### end Alembic commands ###
