"""Migration

Revision ID: eb6c713e8d8b
Revises: 18c9f972de46
Create Date: 2018-09-09 14:38:34.251106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6c713e8d8b'
down_revision = '18c9f972de46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('information', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
